apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blazor-app-front
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: dev
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: blazor-app-front
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - values.yaml
      - values-tag.yaml

