apiVersion: v1
kind: Service
metadata:
  name: "{{ include "blazor-app-front.fullname" . }}-service"
  labels:
    {{- include "blazor-app-front.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "blazor-app-front.selectorLabels" . | nindent 4 }}
